#In Minutes
PlayerKillBantime: 7200

#In Minutes
MonsterKillBantime: 2880

#In Minutes
EnvironmentKillBantime: 2880

BantimeByPlaytime: false
#In Percent
BantimeByPlaytimePercent: 10
#In Minutes
BantimeByPlaytimeMinimumTime: 60
BantimeByPlaytimeMaximumTime: UseAboveTimes

CombatDeath: true
#In Seconds
CombatDeathTime: 60

