#If true, Player will be shown their amount of lives left on respawn
NotifyLivesLeftOnRespawn: true

#In Minutes -1 is disable (0 is unlimited but can only be used if BantimeByPlaytime: true)
PlayerDeathBantime: 7200
MonsterDeathBantime: 2880
EnvironmentDeathBantime: 4320

#If true, above times are used as max ban time
BantimeByPlaytime: false
#In Percent, minimum is 1
BantimeByPlaytimePercent: 10
#In Minutes, minimum is 1
BantimeByPlaytimeInterval: 60
#Linear or Exponential
BantimeByPlaytimeGrowth: Exponential
#In Minutes, minimum is 1
BantimeByPlaytimeMinimumPlayerDeath: 72
BantimeByPlaytimeMinimumMonsterDeath: 28
BantimeByPlaytimeMinimumEnvironmentDeath: 43

#If true, players will die and receive PlayerDeathBantime if they log out while in combat with another player,
#they will also receive PlayerDeathBantime if killed by a monster or environment during this time
CombatLog: true
#In Seconds
CombatLogTime: 10
#chat or bossbar or none
CombatLogWarningStyle: Bossbar