#Should a player be notified with about their lives left after respawn on death?
NotifyOnRespawn: true
#How should dates be shown in the plugin (Only shows on ban screen if implemented in message)?
#'short': (6/15/15, 9:03 CEST)
#'medium': (Jun 15, 2015, 9:03 CEST)
#'long': (Saturday Jun 15, 2015 at 9:03:01 CEST)
SaveDateFormat: medium
#What bantime should players get if killed by player/monster/environment?
#In Minutes, -1 is disable (0 is unlimited but can only be used if BantimeByPlaytime: true).
PlayerDeathBantime: 7200
MonsterDeathBantime: 2880
EnvironmentDeathBantime: 4320


#Should the ban time be calculated by playtime instead?
#If true, above times are used as max ban time.
BantimeByPlaytime: false
#Should time since last death be used instead of total playtime for calculating the bantime?
BantimeByPlaytimeSinceLastDeath: false
#How much % of the BantimeByPlaytimeMinimum will be added to the bantime each BantimeByPlaytimeInterval?
#In Percent, minimum is 1.
BantimeByPlaytimePercent: 10
#At what rate of playtime/time since last death should the bantime increase?
#In Minutes, minimum is 1
BantimeByPlaytimeInterval: 60
#At what rate should the bantime by playtime grow?
#Linear is slow overall, exponential is slow at start but quickly rises.
# -> linear/exponential
BantimeByPlaytimeGrowth: exponential
#What should be the minimum amount of bantime for player/monster/environment deaths?
#In minutes, minimum is 1.
BantimeByPlaytimeMinimumPlayerDeath: 72
BantimeByPlaytimeMinimumMonsterDeath: 28
BantimeByPlaytimeMinimumEnvironmentDeath: 43


#Should players die and receive PlayerDeathBantime if they log out while in combat with another player?
#They will also receive PlayerDeathBantime if killed by a monster or environment during this time.
CombatTag: true
#How long should a player be tagged for after combat?
#In Seconds, minimum is 1.
CombatTagTime: 10
#How should the player be notified when tagged in combat?
#-> chat/bossbar/none
CombatTagWarningStyle: bossbar


#Should players be able to give a life of their own to someone else (players will still need permission to use the revive command)?
#Players who were previously deathbanned will be unbanned if given a life.
Revive: true
#How long should a player be banned for if the player has 0 lives left after giving a revive?
#If player is combat tagged, the player will receive PlayerDeathBantime if BantimeOnReviveDeath has a lower value.
#In minutes, minimum is 1.
BantimeOnReviveDeath: 4320
#How much time should the revive option go on cooldown for after using it?
#In minutes, minumum is 0.
TimeBetweenRevives: 1440
#Should players be able to use the revive option directly on first join?
#If false, players will be able to use revive after TimeBetweenRevives minutes.
ReviveOptionOnFirstJoin: false


#What should the max amount of lives a player can have be?
#minimum is 1
MaxLives: 5